### ISSUE TITLE
Plugin

### ISSUE THREAD

**Issue by ChampOfGamesYT** [jhampt/ServerInfoUI#1]
Do you need help with your plugin?

**Comment by jhampt** [comment]
yes i actually tried using some of your code from rulesui had some issues though using the config with it and form

**Comment by ChampOfGamesYT** [comment]
Do you have discord?

**Comment by jhampt** [comment]
yes i do

**Comment by ChampOfGamesYT** [comment]
Then join at https://discord.gg/g7qdsec

**Comment by jhampt** [comment]
okay im at school when i leave to go home ill get my iphone and join

**Comment by ChampOfGamesYT** [comment]
Perfect if you are there send me a message per dm

**Comment by ChampOfGamesYT** [comment]
Hello?

**Comment by jhampt** [comment]
i forgot after school today i will join ive been so busy unfortunately after school ill join at 3:00 ill join it

**Comment by jhampt** [comment]
Okay?

**Comment by jhampt** [comment]
`lol`

**Comment by ChampOfGamesYT** [comment]
Join

**Comment by jhampt** [comment]
I did
